# Generated by Django 5.0.4 on 2024-08-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_freelancecontract_paymentinstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstallment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
