# Generated by Django 5.0.4 on 2024-08-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_paymentinstallment_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstallment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
