# Generated by Django 5.0.4 on 2024-08-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_project_project_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_repo_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
