# Generated by Django 5.0.4 on 2024-08-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstallment',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
