# Generated by Django 5.0.4 on 2024-08-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_paymentinstallment_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='total_including_gst',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15),
        ),
    ]
