# Generated by Django 5.0.4 on 2024-08-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_freelancecontract_pdf_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancecontract',
            name='pdf_version',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
