# Generated by Django 5.0.4 on 2024-08-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_alter_freelancecontract_pdf_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_review_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='freelancer_review_given',
            field=models.BooleanField(default=False),
        ),
    ]
