# Generated by Django 5.0.4 on 2024-08-31 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_project_client_review_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='adherence_to_deadlines',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='problem_solving_ability',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='professionalism',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_of_work',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
