# Generated by Django 5.0.4 on 2024-08-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
