# Generated by Django 5.0.4 on 2024-07-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
