# Generated by Django 5.0.4 on 2024-08-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google',
            field=models.BooleanField(default=False),
        ),
    ]
