# Generated by Django 5.0.4 on 2024-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='professional_title',
            field=models.TextField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='skills',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
